#!/bin/sh -xe

PKG_CONFIG_LIBS="libffi libxml2 glib"

CFLAGS="-Wno-deprecated"
LDFLAGS=

for lib in $PKG_CONFIG_LIBS ; do
	if [ -z "$PKG_CONFIG_PATH" ] ; then
		PKG_CONFIG_PATH="/usr/local/opt/$lib/lib/pkgconfig"
	else
		PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/$lib/lib/pkgconfig"
	fi
done

export PKG_CONFIG_PATH

for lib in glib intl ; do
	CFLAGS="$CFLAGS -I/usr/local/opt/${lib}/include"
	LDFLAGS="$LDFLAGS -L/usr/local/opt/${lib}/lib"
done

export CFLAGS
export LDFLAGS

. CI/travis/make_linux
